common:
  bootstrap_s3_bucket_name: my-cdk-bootstrap-bucket
  vpc_id: vpc-7531n846v17385e92
  region: ca-central-1
  account: '123456789'

ec2_instances:
  - name: MyInstance
    instance_class: T3
    instance_size: XLARGE
    ami_id: ami-0a123b456c789d012
    subnet_id: subnet-0abc123de456f7890
    security_group_id: sg-0a123b456c789d012
    availability_zone: ca-central-1a